name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        goarch: [amd64, arm64]
        goos: [linux, darwin]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Build the email template
        run: |
          cd email
          pnpm install
          pnpm run export
      - name: Build
        run: go build -o aegle-${{ matrix.goos }}-${{ matrix.goarch }} -ldflags "-w -s -buildid=" -trimpath
        env:
          CGO_ENABLED: 0
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aegle-${{ matrix.goos }}-${{ matrix.goarch }}
          path: aegle-${{ matrix.goos }}-${{ matrix.goarch }}
  post:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: aegle*
          file_glob: true
          draft: true
